title: Hello, chooms.
description: > # this means to ignore newlines until "baseurl:"
  ScourgetheTracker development blog.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://webtool.click" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ScourgetheTracker # add your name
author-img: scourge_the_tracker_by_wyn83.jpg # add your photo
about-author: I'm a developer focusing on back-end development, security, privacy and consuumer digital rights. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: scourgethetracker # add your Github handle
social-linkedin: benvanack # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
